/**
 * Autogenerated by Thrift Compiler (0.12.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef remote_shell_CONSTANTS_H
#define remote_shell_CONSTANTS_H

#include "remote_shell_types.h"



class remote_shellConstants {
 public:
  remote_shellConstants();

};

extern const remote_shellConstants g_remote_shell_constants;



#endif
