// This autogenerated skeleton file illustrates how to build a server.
// You should copy it to another filename to avoid overwriting it.

#include "RemoteShellService.h"
#include <thrift/protocol/TBinaryProtocol.h>
#include <thrift/server/TSimpleServer.h>
#include <thrift/transport/TServerSocket.h>
#include <thrift/transport/TBufferTransports.h>

using namespace ::apache::thrift;
using namespace ::apache::thrift::protocol;
using namespace ::apache::thrift::transport;
using namespace ::apache::thrift::server;

using namespace  ::cxx::service;

class RemoteShellServiceHandler : virtual public RemoteShellServiceIf {
 public:
  RemoteShellServiceHandler() {
    // Your initialization goes here
  }

  void GetComputerInfo(ComputerInfo& _return) {
    // Your implementation goes here
    printf("GetComputerInfo\n");
  }

  void GetCpuInfo(CpuInfo& _return) {
    // Your implementation goes here
    printf("GetCpuInfo\n");
  }

  void GetMemoryInfo(MemoryInfo& _return) {
    // Your implementation goes here
    printf("GetMemoryInfo\n");
  }

  void GetDiskInfo(DiskInfo& _return) {
    // Your implementation goes here
    printf("GetDiskInfo\n");
  }

  void GetNetworkInfo(NetworkInfo& _return) {
    // Your implementation goes here
    printf("GetNetworkInfo\n");
  }

  void Execute(ShellRtn& _return, const std::string& cmdWithArgs) {
    // Your implementation goes here
    printf("Execute\n");
  }

};

int main(int argc, char **argv) {
  int port = 9090;
  ::apache::thrift::stdcxx::shared_ptr<RemoteShellServiceHandler> handler(new RemoteShellServiceHandler());
  ::apache::thrift::stdcxx::shared_ptr<TProcessor> processor(new RemoteShellServiceProcessor(handler));
  ::apache::thrift::stdcxx::shared_ptr<TServerTransport> serverTransport(new TServerSocket(port));
  ::apache::thrift::stdcxx::shared_ptr<TTransportFactory> transportFactory(new TBufferedTransportFactory());
  ::apache::thrift::stdcxx::shared_ptr<TProtocolFactory> protocolFactory(new TBinaryProtocolFactory());

  TSimpleServer server(processor, serverTransport, transportFactory, protocolFactory);
  server.serve();
  return 0;
}

