/**
 * Autogenerated by Thrift Compiler (0.12.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef remote_shell_service_CONSTANTS_H
#define remote_shell_service_CONSTANTS_H

#include "remote_shell_service_types.h"

namespace cxx { namespace service {

class remote_shell_serviceConstants {
 public:
  remote_shell_serviceConstants();

};

extern const remote_shell_serviceConstants g_remote_shell_service_constants;

}} // namespace

#endif
